config:
  data:
    input_data:
      clear: true
      movielens:
        use: true
        type: ml-1m
        path: /tmp/cf_experiments_loop/dataset/movielens
        transformations: cf_experiments_loop.transformations.movielens.prepare_data
      goodreads:
        use: false
        type: goodreads
        transformations: cf_experiments_loop.transformations.goodreads.get_goodreads_data
      bookcrossing:
        use: false
        type: bookcrossing
        transformations: cf_experiments_loop.transformations.bookcrossing.bookcrossing_converting
      behance:
        use: false
        type: behance
        transformation: cf_experiments_loop.transformations.behance.behance_converting
      user_item_data:
        use: false
        end_date: 01-05-2020
        period: 2
        data_path: ./data
        users_number: 100
        transformation: cf_experiments_loop.transformations.user_time_data.user_item_transform

  model:
    model: [
      cf_experiments_loop.models.svdpp.svdpp,
      cf_experiments_loop.models.ncf.ncf_model,
      cf_experiments_loop.models.mf.mf,
      cf_experiments_loop.models.svd.svd,
    ]
    loss: cf_experiments_loop.losses.mean_squared_error
    metrics: [
      cf_experiments_loop.metrics.accuracy,
      cf_experiments_loop.metrics.rmse,
      cf_experiments_loop.metrics.mae
    ]
    batch_size: [1024, 2048, 4096]
    epoch: [50, 100, 200]
    optimizers: adam
    grid_search: True
    learning_rate: 0.01


  result:
    model: /tmp/cf_experiments_loop/model/
    log: /tmp/cf_experiments_loop/log/
    results_csv: run_results.csv
    log_to_ml_flow: True
    clear: true
