config:
  data:
    input_data:
      clear: true
      movielens:
        use: true
        type: ml-20m
        path: /tmp/cf_experiments_loop/dataset/movielens
        transformations: cf_experiments_loop.transformations.movielens.prepare_data
      goodreads:
        use: false
        type: goodreads
        transformations: cf_experiments_loop.transformations.goodreads.get_goodreads_data
      bookcrossing:
        use: false
        type: bookcrossing
        transformations: cf_experiments_loop.transformations.bookcrossing.bookcrossing_converting
      behance:
        use: false
        type: behance
        transformation: cf_experiments_loop.transformations.behance.behance_converting
  model:
    model: [
      cf_experiments_loop.models.embedding.embedding_model,
      cf_experiments_loop.models.ncf.ncf_model,
      cf_experiments_loop.models.mf.mf,
      cf_experiments_loop.models.svd.svd,
    ]
    loss: cf_experiments_loop.losses.mean_squared_error
    metrics: [
      cf_experiments_loop.metrics.accuracy,
      cf_experiments_loop.metrics.rmse,
      cf_experiments_loop.metrics.mae
    ]
    batch_size: [128, 256]
    epoch: [20, 30]
    optimizers: adam
    grid_search: True


  result:
    model: /tmp/cf_experiments_loop/model/
    log: /tmp/cf_experiments_loop/log/
    results_csv: run_results.csv
    log_to_ml_flow: True
    clear: true
