config:
  data:
    input_data:
      clear: true
      movielens:
        use: true
        type: ml-1m
        path: /tmp/cf_experiments_loop/dataset/movielens
      transformations: cf_experiments_loop.transformations.movielens.prepare_data
  model:
    model: cf_experiments_loop.models.mf.mf
    loss: cf_experiments_loop.losses.mean_squared_error
    metrics: [
      cf_experiments_loop.metrics.accuracy
    ]
    batch_size: 250
    epoch: 30

  result:
    model: /tmp/cf_experiments_loop/model/
    log: /tmp/cf_experiments_loop/log/
    clear: true
